Add info how to connect to internal server via proxied ssh
Otus-DevOps-2021-02/acidlynx_infra pull request #2
Opened 2021-03-17 11:14 UTC by acidlynx

# Выполнено ДЗ № 5

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Добавлены ресурсы в яклауд
 - Добавлена информация, как сконфигурить локальный ssh, чтобы можно было получить быстрый доступ до bastion и до someinternalhost
 - 

## Как запустить проект:
 - Пока только проверить корректность добавленной информации в README.md

## Как проверить работоспособность:
 - Довериться тому, что команды работают )

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2021-03-17 12:07 UTC, mrgreyves requested changes
Здравствуйте!) В вашем пр определенно не хватает файлов, рекомендую свериться с методичкой к ДЗ. ДЗ возвращаю на доработку.

2021-03-17 12:31 UTC, acidlynx commented
> Здравствуйте!) В вашем пр определенно не хватает файлов, рекомендую свериться с методичкой к ДЗ. ДЗ возвращаю на доработку.

Да. Это старая привычка - как сделал ветку, сразу делать драфт PR, чтобы тесты гонялись при каждом коммите.

2021-03-17 13:13 UTC, mrgreyves commented
Тогда как вариант к сообщению стоит добавлять WIP =)

2021-03-18 07:37 UTC, mrgreyves approved these changes
Здравствуйте!) Проверил ваше дз. Задания выполнены корректно, вполне возможно возникла проблема на уровне сетевой связности с провайдером. ДЗ принимаю!=)

2021-03-18 07:38 UTC, acidlynx commented
> Здравствуйте!) Проверил ваше дз. Задания выполнены корректно, вполне возможно возникла проблема на уровне сетевой связности с провайдером. ДЗ принимаю!=)

Отлично! Спасибо! )

2021-03-18 07:38 UTC, merged